name: Auto-Close Sentry Issue

on:
  issues:
    types: [closed]

jobs:
  close_sentry:
    name: Auto-Close Sentry Issue
    runs-on: ubuntu-latest
    if: github.event.issue.body != null && contains(github.event.issue.body, 'https://space-dashboard.sentry.io/issues/')
    steps:
      - name: Extract Sentry Issue ID from Body
        id: extract
        run: |
          BODY="${{ github.event.issue.body }}"

          # Extract the Sentry issue URL
          URL=$(echo "$BODY" | grep -oE 'https://space-dashboard.sentry.io/issues/[0-9]+')

          # Validate the extracted URL
          if [ -z "$URL" ]; then
            echo "No valid Sentry issue URL found in the issue body."
            exit 1
          fi

          # Extract the Sentry issue ID from the URL
          ID=$(echo "$URL" | grep -oE '[0-9]+$')

          # Validate the extracted ID
          if [ -z "$ID" ]; then
            echo "No valid Sentry issue ID found in the extracted URL."
            exit 1
          fi

          echo "Extracted Sentry issue URL: $URL"
          echo "Extracted Sentry issue ID: $ID"

          # Output the ID for the next step
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Mark Sentry Issue as Resolved
        run: |
          ISSUE_ID=${{ steps.extract.outputs.id }}
          echo "Resolving Sentry issue: $ISSUE_ID"

          curl -s -X PUT \
            -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status": "resolved"}' \
            "https://sentry.io/api/0/issues/$ISSUE_ID/"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_WRITE }}
