name: Auto-Close Sentry Issue

on:
  issues:
    types: [closed]

jobs:
  close_sentry:
    name: Auto-Close Sentry Issue
    runs-on: ubuntu-latest
    if: github.event.issue.body != null && contains(github.event.issue.body, 'https://space-dashboard.sentry.io/issues/')
    steps:
      - name: Extract Sentry Issue ID from Body
        id: extract
        run: |
          BODY="${{ github.event.issue.body }}"

          # Extract the Sentry issue ID from a <sentryid> tag
          ID=$(echo "$BODY" | grep -oE '<sentryid>[0-9]+</sentryid>' | grep -oE '[0-9]+')

          if [ -z "$ID" ]; then
            echo "No valid <sentryid> tag found in the issue body."
            exit 1
          fi

          echo "Extracted Sentry issue ID: $ID"
          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Mark Sentry Issue as Resolved
        run: |
          ISSUE_ID=${{ steps.extract.outputs.id }}
          echo "Resolving Sentry issue: $ISSUE_ID"

          curl -s -X PUT \
            -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status": "resolved"}' \
            "https://sentry.io/api/0/issues/$ISSUE_ID/"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN_WRITE }}
