name: Close Sentry Issue When GitHub Issue is Closed

on:
  issues:
    types: [closed]

jobs:
  close_sentry:
    runs-on: ubuntu-latest
    if: github.event.issue.body != null && contains(github.event.issue.body, 'https://sentry.io/')
    steps:
      - name: Extract Sentry Issue ID from Body
        id: extract
        run: |
          BODY="${{ github.event.issue.body }}"
          URL=$(echo "$BODY" | grep -oE 'https://sentry.io/organizations/.*/issues/[0-9]+')
          ID=$(echo "$URL" | grep -oE '[0-9]+$')

          if [ -z "$ID" ]; then
            echo "No Sentry issue ID found."
            exit 1
          fi

          echo "id=$ID" >> $GITHUB_OUTPUT

      - name: Mark Sentry Issue as Resolved
        run: |
          ISSUE_ID=${{ steps.extract.outputs.id }}
          echo "Resolving Sentry issue: $ISSUE_ID"

          curl -s -X PUT \
            -H "Authorization: Bearer $SENTRY_AUTH_TOKEN" \
            -H "Content-Type: application/json" \
            -d '{"status": "resolved"}' \
            "https://sentry.io/api/0/issues/$ISSUE_ID/"
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
