name: Changeset Check
permissions:
  contents: read

on:
  pull_request:
    branches: [main]
    paths:
      - '**/*'
      - '!.changeset/**/*'
      - '!.github/workflows/**/*'

# Skip this workflow for release PRs (created by the release workflow)
# which come from the changeset-release/main branch

jobs:
  check:
    name: Check for changeset
    runs-on: ubuntu-latest
    # Skip if this is a release PR (from changeset-release/main branch)
    if: github.head_ref != 'changeset-release/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # 4.2.2
        with:
          fetch-depth: 0

      - name: Check for changeset files
        id: changeset-check
        run: |
          # Check if there are any .md files in the .changeset directory
          if [ -z "$(find .changeset -name '*.md' -type f -not -path '*/.*')" ]; then
            echo "::error::No changeset found! Please add a changeset using 'yarn changeset:add'"
            echo "has_changeset=false" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "Changeset found"
            echo "has_changeset=true" >> $GITHUB_OUTPUT
          fi
