on:
  push:
    branches:
      - main

name: Deploy to production
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v3
      - name: Use Node.js 16.20.0
        uses: actions/setup-node@v2
        with:
          node-version: 16.20.0
      - name: Build Project
        run: |
          npm install
          npm run build
      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.PROD_FTP_USERNAME }}
          password: ${{ secrets.PROD_FTP_PASSWORD }}
          server-dir: public_html/
          local-dir: ./build/
