name: Staging Deploy

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version/tag to deploy (e.g., v2.0.2) or "latest" for most recent release'
        required: false
        default: 'latest'

permissions:
  contents: read
  packages: read
  actions: write
  deployments: write
  id-token: write

concurrency:
  group: staging-deploy-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy to Staging
    uses: ./.github/workflows/deploy.yml
    with:
      environment: Staging
      version: ${{ github.event.inputs.version || 'latest' }}
    secrets:
      GH_PR_CREATE: ${{ secrets.GH_PR_CREATE }}
      SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
